/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package deliveryteaminkotlin

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

class TeamTest {
    @Test fun should_assign_members_to_team() {
        val team = Team()
        team.apply {
            assignMember(Dev("yanmin"))
            assignMember(BA("xixi"))
            assignMember(QA("shanshan"))
        }

        assertEquals(3, team.getAllMembers().size)
    }

    @Test fun should_assign_stories_to_team() {
        val team = Team()
        team.assignStory(Story("fix bug"))

        assertEquals(1, team.getAllStories().size)
    }

    @Test fun should_get_members_by_lambda_filter() {
        val team = Team()
        team.apply {
            assignMember(Dev("yanmin"))
            assignMember(BA("xixi"))
            assignMember(QA("shanshan"))
        }

        assertEquals("yanmin", team.getMembers {it is Dev}[0].name)
        assertEquals("xixi", team.getMembers { it is BA }[0].name)
        assertEquals("shanshan", team.getMembers { it is QA }[0].name)
        assertEquals(2, team.getMembers { it.name.contains("a") }.size)
    }
}
