/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package deliveryteaminkotlin

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

class TeamTest {
    @Test fun should_assign_members_to_team() {
        val team = Team()

        team.assignMember(Dev("yanmin"))
        val allMembers = team.getAllMembers()

        assertEquals(1, allMembers.size)

    }
}
