/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package deliveryteaminkotlin

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

class TeamTest {
    @Test fun should_assign_members_to_team() {
        val team = Team()

        team.assignMember(Dev("yanmin"))
        team.assignMember(BA("xixi"))
        team.assignMember(QA("shanshan"))
        val allMembers = team.getAllMembers()

        assertEquals(3, allMembers.size)
    }

    @Test fun should_assign_stories_to_team() {
        val team = Team()

        team.assignStory(Story("fix bug"))
        val allStories = team.getAllStories()

        assertEquals(1, allStories.size)
    }
}
